# edit this if not me
SHADOWRUN_CP_FOLDER=/usr/matt/media/malexa/steam/steamapps/common/Shadowrun\ Dragonfall\ Director\'s\ Cut/Dragonfall_Data/StreamingAssets/ContentPacks/

.PHONY: all

all:
	cp -r ./Way\ of\ the\ Gun\ Adept $(SHADOWRUN_CP_FOLDER)
